sudo: required

language: ruby

services:
  - docker

env:
  - VERSION=latest
  - VERSION=5.4
  - VERSION=5.4-apache
  - VERSION=5.4-fpm
  - VERSION=5.5
  - VERSION=5.5-apache
  - VERSION=5.5-fpm
  - VERSION=5.6
  - VERSION=5.6-apache
  - VERSION=5.6-fpm
  - VERSION=7.0
  - VERSION=7.0-apache
  - VERSION=7.0-fpm
  - VERSION=7.1
  - VERSION=7.1-apache
  - VERSION=7.1-fpm
  - VERSION=7.2
  - VERSION=7.2-apache
  - VERSION=7.2-fpm

install:
- travis_wait 30 make build VERSION=${VERSION}
- if [ "$NO_DEV" != "1" ]; then travis_wait 30 make -C dev build VERSION=${VERSION}; fi

script:
- make test VERSION=${VERSION}
- if [ "$NO_DEV" != "1" ]; then travis_wait 30 make -C dev test VERSION=${VERSION}; fi
